### ISSUE TITLE
TLS 1.2 support

### ISSUE THREAD

**Issue by guiwoda** [thephpleague/omnipay-paypal#103]
According to https://devblog.paypal.com/upcoming-security-changes-notice/ Paypal is turning off SSL support in June 17, but I'm receiving errors from apps on sandbox right now as well.

Should we expect the library to change to TLS 1.2 by default?
Is there anything I can do to help you with that?

Cheers!

**Comment by DMeganoski** [comment]
Yes, I have been getting errors on our test server for about a week, though oddly not from my local machine. The test server is not my personal paypal account, though.

I need this to continue testing my application, though. D: 

I can try using my personal sandbox credentials, but I fear that account is soon to be affected as well. Does anyone know of a temporary fix?

**Comment by guiwoda** [comment]
You can pass a customized Guzzle\Http\Client with CURLOPT_SSLVERSION => 6
to work around it. (6 is CURL_SSLVERSION_TLSv1_2 but somehow I didn't have
it declared in php 5.6.12).

**Comment by delatbabel** [comment]
What you will probably need to do as well, and what we ended up having to do, is to upgrade our version of libcurl and related libraries to support TLS 1.2.  The version of TLS is actually auto-negotiated by the client (curl) and the server (apache/nginx/whatever) so if your libcurl doesn't support TLS 1.2 you're going nowhere.

If you're on CentOS 6 for example, the supplied libcurl does not support TLS 1.2.  Try this:

```
rpm -Uvh http://www.city-fan.org/ftp/contrib/yum-repo/city-fan.org-release-1-12.rhel6.noarch.rpm
yum -y install libcurl
yum -y update
```

**Comment by delatbabel** [comment]
My understanding is that libcurl versions > 7.40 should do the trick. libcurl for CentOS 6 is 7.19.

**Comment by DMeganoski** [comment]
My local machine has 7.39, I'll have to check the server. Thanks for the tips, I'll see if I can get this working later today.

**Comment by guiwoda** [comment]
It works on CentOS with libcurl v7.19.7-46

**Comment by Elodis** [comment]
I've updated ran a composer update, confirmed latest version of omnipay/paypal as well as performed the libcurl update instructions above:

Package libcurl-7.47.0-1.0.cf.rhel6.x86_64 already installed and latest version

Still getting the "[curl] 35" error when using Sandbox.  No mention of the SSLv3 error however as in https://github.com/thephpleague/omnipay-paypal/issues/104

Any Ideas?

Also, the rpm address you mention http://www.city-fan.org/ftp/contrib/yum-repo/city-fan.org-release-1-12.rhel6.noarch.rpm has since been moved and now causes a 404.. I grabbed:

http://www.city-fan.org/ftp/contrib/yum-repo/city-fan.org-release-1-13.rhel6.noarch.rpm

**Comment by delatbabel** [comment]
Ah OK -- yes a http restart would be required to pick up the newer version of libcurl, in fact I would be inclined to do a reboot when updating such a low level library as it could be embedded in all sorts of stuff.

**Comment by lukeholder** [comment]
Since this was top result in my search, I will leave this here for MAMP users with this issue: https://github.com/paypal/PayPal-PHP-SDK/issues/484#issuecomment-176240130
