### ISSUE TITLE
Credit Card landing page is not working in Express Checkout

### ISSUE THREAD

**Issue by vigneshpalanivel** [thephpleague/omnipay-paypal#149]
I tried the SolutionType and LandingPage parameter, but, still its not working.

$this->omnipay->setSolutionType('Sole'); 
$this->omnipay->setLandingPage('Billing');

**Comment by delatbabel** [comment]
It's not clear from the above code what the problem is. Can you give us some more context?  e.g. how do you create the $this->omnipay object?

Can you be more clear as to what you mean by "not working"?  "Not working" could possibly mean any of the following:

* The landing page shown is not the exact correct shade of blue.
* The parameter is ignored and the regular landing page is shown instead.
* PayPal shows an error message which I have neglected to provide here.
* The code throws an exception and exits.
* The server catches fire.
* The universe ends.

(I admit that these examples are silly but just to illustrate that the phrase "not working" doesn't help. As a developer yourself I expect that you already understand that.)

**Comment by vigneshpalanivel** [comment]
This is how I create Omnipay object, $this->omnipay  = Omnipay::create($gateway);

I'm getting regular landing page which has PayPal Email address and Password. But, I need to show Debit/Credit Card filling page.

I'm not getting any error page or warning page, just that code is not showing Debit/Credit Card filling page.

**Comment by delatbabel** [comment]
> I'm getting regular landing page which has PayPal Email address and Password. But, I need to show Debit/Credit Card filling page.

I'm not aware of any method to do that using PayPal Express.

**Comment by vigneshpalanivel** [comment]
I already tried it before 2 months, it was working. But, now, its not showing Card fields.

If issue in this script, please fix it and open this issue. Now, its in Closed status.
