### ISSUE TITLE
PayPalExpress handling refunds?

### ISSUE THREAD

**Issue by tonypartridge** [thephpleague/omnipay-paypal#169]
Hey Guys,

Struggling on this one. I've got the API working quite easily out of the box. But I am struggling to fathom out how we handle Refunds/Pending transactions with PayPal Express.

There doesn't seem to be a way to set the NotifyURL or invoice within $gateway->purchase();

Does anyone have any example code of how they have achieved managing refunds, partial refunds, pending transactions etc?

Many thanks
Tony

**Comment by leith** [comment]
You can add the notification URL by adding the 'notifyUrl' field to your request fields. So it would look something like:
```php
$gateway->purchase([
    // ... normal fields passed to request, e.g. amount ...
    'notifyUrl' => 'http://example.com/notify',
]);
```

I haven't handled refunds yet, but I have done pending transactions (ones that aren't declined but aren't successful yet because they need review) - I forked and added an `isPending()` method to the abstract response to handle this, so my workflow is now:
```php
if ($response->isPending()) {
    // handle 'pending' result
} else if ($response->isSucessful()) {
    // handle 'success' result
} else {
    // handle 'fail' or 'error' result
}
```

**Comment by tonypartridge** [comment]
Hey @leith ,

Have you tested that working?

I was using:

`		$response = $gateway->purchase(
			[
				'amount'    => $data->amount,
				'currency'  => $data->currency,
				'invoice'   => $data->invoice,
				'item_name' => htmlspecialchars($data->title . " - " . $data->start_date),
				'cancelUrl' => "https://my_url.com"
				'notifyUrl' => "https://my_url.com",
				'returnUrl' => "https://my_url.com"
			]
		)->send();`

But it wasn't working. I had to hard set the IPN Notifications URL which isn't any good for our scenario.

isPending is actually in OmniPay now, I am using it see:

`		if (!$response->isSuccessful())
		{
			throw new Exception($response->getMessage());
		}
		else
		{

			if ($response->isPending())
			{
				// pending sale flow
				$transaction->logdata = 'Transaction is Pending, please check your PayPal Account: ' . $response->getMessage(); // Any message the gateway his given us.
			}
			else if ($response->isSuccessful())
			{
				// normal successful flow
				$transaction->logdata      = 'Payment was Successful: ' . $response->getMessage();
				$transaction->paymentstate = 1;

				$send_cm = true;

			}
			else if ($response->isRedirect())
			{
				// redirect back to PayPal since there was a payment error, i.e. funding source
				$app->redirect($response->getRedirectUrl());

				return;
			}
			else
			{
				// normal failure flow
				$transaction->logdata = 'There was an error, PayPal responded with: ' . $response->getMessage(); // Any message the gateway his given us.

			}
		}`

And it works well. I'm just struggling with the IPN Responses.

Many thanks
Tony

**Comment by leith** [comment]
Yes I tested this and did not need to use a hard-coded URL in my PayPal config settings. In our case the notify URL changes with each sale as the notification URL includes the sale ID as well. I found the PayPal IPN sandbox really useful for testing callbacks to our servers. As you point out, this will be from `completePurchase` though - there's no transaction to send IPN messages from just using `purchase` as that just contains the redirect information for a _potential_ transaction. For a redirect-based gateway like PayPal Express, the flow here should be `purchase -> redirect to PayPal -> redirect back -> completePurchase`. You would never get a 'pending' response until the `completePurchase` part of the process. Since the `purchase` and `completePurchase` calls should also never share their response callback (`if ($response->isSuccessful())...` etc.), there would be no need to overlap, or have an `isPending` check during the `purchase` process.

I think in the flow you've outlined, the outer 'is not successful' check is redundant - nothing except successful transactions will work as intended. If you shift your exception throwing to your normal failure flow in the `else` block, that wold make more sense.

Note that this is a different flow from a payment gateway where you take the card details to submit to the gateway, as that (typically) only uses `purchase` and not `completePurchase` since the user never leaves your site.

**Comment by tonypartridge** [comment]
Ok so I have got it working, but specifying the notifyUrl on purchase() doesn't work. It only works if I pass it in on completePurchase.

**Comment by delatbabel** [comment]
> Ok so I have got it working, but specifying the notifyUrl on purchase() doesn't work. It only works if I pass it in on completePurchase.

That is what I would expect from PayPal.  Generally things don't work unless they are specified on the completePurchase() call.  I guess with PayPal they get so many purchase() calls that never end up being a real transaction (these just create a redirect URL to send the customer to the PayPal login, a lot of customers do that and never pay) that they decided that everything has to be on completePurchase().

Another example is that the transactionReference received on a purchase() call can be pretty much ignored.  If you want to do a refund then you have to use the transactionReference received in the response from completePurchase.

**Comment by tonypartridge** [comment]
Yep exactly what I found… we should probably write a guide on using the PayPal plugin given everything I’ve read online is help requests and this and that. Whilst I appreciate OmniPay is focused for developers, if you are not used to OmniPay it takes some time working it all out.

**Comment by judgej** [comment]
@tonypartridge Even a few lines of explanation in a PR (from everybody!) will help to fatten up the documentation over time. There is just too much of it for a small team to keep maintained alone.
