### ISSUE TITLE
Authorization only with redirect example.

### ISSUE THREAD

**Issue by 3even** [thephpleague/omnipay-paypal#38]
Is there an authorization with redirect example available?
I can get the redirect working but only for capture(final sale) but not authorization only.

```
$formData = [
    'number' => '4242424242424242',
    'expiryMonth' => '6',
    'expiryYear' => '2016',
    'cvv' => '123'
];

$response = $gateway->authorize([
    'amount' => '10.00',
    'card' => $formData,
    'returnUrl' => 'https://www.example.com/return',
    'cancelUrl' => 'https://www.example.com/cancel'
])->send();

```

**Comment by delatbabel** [comment]
You need to provide a credit card object instead of the array.  I have submitted a PR with an example in the header of RestAuthorizeRequest.php.  Here is the example code in full:

<code>
 *   // Create a credit card object
 *   // DO NOT USE THESE CARD VALUES -- substitute your own
 *   // see the documentation in the class header.
 *   $card = new CreditCard(array(
 *               'firstName' => 'Example',
 *               'lastName' => 'User',
 *               'number' => '4111111111111111',
 *               'expiryMonth'           => '01',
 *               'expiryYear'            => '2020',
 *               'cvv'                   => '123',
 *               'billingAddress1'       => '1 Scrubby Creek Road',
 *               'billingCountry'        => 'AU',
 *               'billingCity'           => 'Scrubby Creek',
 *               'billingPostcode'       => '4999',
 *               'billingState'          => 'QLD',
 *   ));
 *
 *   // Do an authorisation transaction on the gateway
 *   $transaction = $gateway->authorize(array(
 *       'amount'        => '10.00',
 *       'currency'      => 'AUD',
 *       'description'   => 'This is a test authorize transaction.',
 *       'card'          => $card,
 *   ));
 *   $response = $transaction->send();
 *   if ($response->isSuccessful()) {
 *       echo "Authorize transaction was successful!\n";
 *       // Find the authorization ID
 *       $auth_id = $response->getTransactionReference();
 *   }
</code>

**Comment by delatbabel** [comment]
Note that if you're passing in card data you don't need to send in a returnUrl or a cancelUrl and in any case these are ignored by the class.

**Comment by 3even** [comment]
@delatbabel Thanks!
