### ISSUE TITLE
recurring payments

### ISSUE THREAD

**Issue by freimanas** [thephpleague/omnipay-paypal#70]
It would be really nice to have this ont he readme:

TODO: Billing Plans and Agreements -- set up recurring payments.

it was frustrating going through the code and seeing that recurring is still in TODO list...

**Comment by judgej** [comment]
Any of these drivers can be extended by any third party. If there are any people who would collectively like to give this a go, then they would get plenty of help here. However, since recurring payments are a currently out of scope of what OmniPay is attempting to do right now, it is difficult to see how this could be squeezed in to the limited time people have. But someone with a scratch to itch could well get this started either on a clone of their own, or an extension driver that sits on top of the standard driver.

**Comment by kayladnls** [comment]
I added an out of scope clause thing to the readme.
