### ISSUE TITLE
Please add means for me to get the buyers email after transaction complete.

### ISSUE THREAD

**Issue by najela** [thephpleague/omnipay-paypal#71]
After completing my payments with `gateway->completePurchase($params)->send()`, There is no way to get the buyers email for the paypal transaction?

**Comment by barryvdh** [comment]
Doesn't it exist in the response data?

    $response = $gateway->completePurchase($params)->send();
    $data = $response->getData();
    print_r($data);

Probably something like `$data['payer']['payer_info']['payer_info']`?

See the example data from https://raw.githubusercontent.com/thephpleague/omnipay-paypal/master/tests/Mock/RestCompletePurchaseSuccess.txt

**Comment by najela** [comment]
@barryvdh  It doesn't in the response data.

**Comment by newuser50938** [comment]
Would like this as well, pretty important!
Checked it myself and i didn't see anything that contained payers email address..

**Comment by najela** [comment]
@newuser50938  maybe its a limitation from Paypal. I had no choice but to use the IPN thing :wink:

**Comment by newuser50938** [comment]
@najela it's not, it's very possible to get the email address from express checkout as well
GetExpressCheckoutDetailsResponseDetails->PayerInfo->Payer, but it seems omnipay doesn't return any of payerinfo details...

**Comment by delatbabel** [comment]
Wouldn't it be better for your application to get the buyer's details, including email address, etc, from the purchaser at time of purchase rather than relying on PayPal's data?  Your customer may wish to use a different email address to communicate with your store than they use as their address when logging in to PayPal.  I have multiple email addresses that I use for different accounts and I don't, for example, want my PayPal address to start being used by some random shop owner for their sales email receipts and promotional emails.

We have already discussed this issue when it relates to customer addresses -- the customer may have their home address registered with PayPal (and you can get this through the express gateway) but may wish your store to send the purchased product to a completely different address, e.g. partner's address for purchase of flowers or other gifts, work address, etc.

**Comment by najela** [comment]
@delatbabel Yep. I'm actually interested in getting the buyer's paypal email so I can do my own analysis. Its not like I'm relying completely on that email.

**Comment by delatbabel** [comment]
OK the answer is as follows:

* It is not in the data returned by the Express gateway.  If you need the customer's PayPal email address and you are using the Express gateway I suggest that you switch to the REST gateway. In any case both PayPal Express and PayPal Pro have been superseded by PayPal REST and are likely to be deprecated at some point in the future.  There is nothing that we can do in omnipay-paypal to return data to you that is not provided by the gateway.

* In the REST gateway it is only available after calling completePurchase().  As @barryvdh points out it is $data['payer']['payer_info']['email']

Ticket can be closed.

**Comment by hulk66049** [comment]
It took a while for me to figure this one out, but the ability to get this information is already there. You just have to do use following, for $parameters, you'll want to pass in the token.

$response = $gateway->fetchCheckout($parameters)->send();
$data = $response->getData();
