### ISSUE TITLE
Paypal REST completePurchase parameters

### ISSUE THREAD

**Issue by newuser50938** [thephpleague/omnipay-paypal#73]
For the completePurchase parameters, why do we have to pass them?
The completePurchase parameters are simply grabbed from the url parameters "PayerID" and "transcationReference", correct? Why doesn't it do it automaticially or is to keep consistency? I'm just trying to make sure I am PASSING the correct values.

**Comment by delatbabel** [comment]
The REST completePurchase request is independent of your application code which receives the GET response on the URL that PayPal redirects the customer to on payment.  Omnipay can't grab the URL parameters from your application, only your application can get those. So your application needs to pass the transactionReference and payerId to Omnipay so that it can send them on to PayPal.

**Comment by HarryBosh** [comment]
I have a problem in the mentioned area, could someone please advise how to get approval?
http://stackoverflow.com/questions/33358307/omnipay-paypal-rest-with-laravel-5

**Comment by kayladnls** [comment]
@delatbabel is correct.
