### ISSUE TITLE
Documentation for instantiating the adapter is wrong?

### ISSUE THREAD

**Issue by burzum** [thephpleague/omnipay-paypal#81]
[The documentation here](https://github.com/thephpleague/omnipay-paypal/blob/master/src/RestGateway.php#L76) says this:

```php
 $gateway = Omnipay::create('RestGateway');
```

Which results in this error message for me:

> Class '\Omnipay\RestGateway\Gateway' not found

Why is it looking for `RestGateway\Gateway`? My composer.json has this line `"omnipay/paypal": "~2.0",` and the files are in place.

**Update:** I 've a made guess how this works and tried it with `'PayPal\Rest'` and made it work this way. The documentation should be updated.

Honestly, from previous experiences with the older versions of Omnipay, I feel all the adapter configuration seems to be pretty inconsistent any way. Depending on where you look you get slightly different instructions on how to set things up.

**Comment by delatbabel** [comment]
Thanks for the notification, I have just submitted a PR to fix this.  In fact the correct instantiation is to use "PayPal_Rest" although "PayPal\Rest" will also work because _ gets swapped for \ in the instantiation.

I believe that in the general case the correct instantiation is always:

```
$gateway = Omnipay::create($gateway_name);
$gateway->initialize($gateway_data);
```

It seems to be reasonably common for applications to store the $gateway_name and $gateway_data either in configuration parameters or in a database table with $gateway_data stored as a JSON string and then unpacked into a PHP array at gateway initialization time.

PR #84 is incorrect, please use PR #85

**Comment by delatbabel** [comment]
PR has been merged, so this issue can be closed.

**Comment by burzum** [comment]
:+1: thanks.
